version: "3.7"

services:
  web:
    build: .
    command: python3 /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=fake_password
volumes:
  postgres_data:
# version: '3.7'

# services:
#     web:
#         build: .
#         command: python /code/manage.py runserver 0.0.0.0:8000
#         volumes:
#             - .:/code
#         ports:
#             - 8000:8000
#         depends_on:
#             - db
#     db:
#         image: postgres:11
#         volumes:
#             - postgres_data:/var/lib/postgresql/data/
# volumes:
#     postgres_data:
